"""courses table

Revision ID: 634fc790f7bc
Revises: b4e4c3d4bc99
Create Date: 2019-03-10 18:15:17.087375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634fc790f7bc'
down_revision = 'b4e4c3d4bc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
